// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const ElTag: typeof import('element-plus/es')['ElTag']
}
