// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/manage/admin.vue')['default']
    Appversionmanage: typeof import('./src/components/scm/appversionmanage.vue')['default']
    Background: typeof import('./src/components/foundation/background.vue')['default']
    Book: typeof import('./src/components/book/book.vue')['default']
    Bookbox: typeof import('./src/components/book/bookbox.vue')['default']
    Bookcontent: typeof import('./src/components/book/bookcontent.vue')['default']
    Bookinfo: typeof import('./src/components/book/bookinfo.vue')['default']
    Bookshelfbox: typeof import('./src/components/book/bookshelfbox.vue')['default']
    BottomLine: typeof import('./src/components/foundation/bottomLine.vue')['default']
    Camera: typeof import('./src/components/camera.vue')['default']
    Cataloguebox: typeof import('./src/components/book/cataloguebox.vue')['default']
    CommitInfo: typeof import('./src/components/scm/commitInfo.vue')['default']
    Commits: typeof import('./src/components/scm/commits.vue')['default']
    CommonHeader: typeof import('./src/components/header/commonHeader.vue')['default']
    Config: typeof import('./src/components/manage/config.vue')['default']
    DrakMode: typeof import('./src/components/DrakMode.vue')['default']
    Drawer: typeof import('./src/components/scm/drawer.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FaceRecognition: typeof import('./src/components/FaceRecognition.vue')['default']
    Footer: typeof import('./src/components/footer/footer.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    HeaderHome: typeof import('./src/components/header/headerHome.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Like: typeof import('./src/components/like.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Music: typeof import('./src/components/music.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    Notfound: typeof import('./src/components/notfound.vue')['default']
    Repository: typeof import('./src/components/scm/repository.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scm: typeof import('./src/components/scm/scm.vue')['default']
    Scmlogin: typeof import('./src/components/scm/scmlogin.vue')['default']
    SearchHeader: typeof import('./src/components/header/searchHeader.vue')['default']
    Spy: typeof import('./src/components/game/spy.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    VersionHistory: typeof import('./src/components/scm/versionHistory.vue')['default']
    Watch: typeof import('./src/components/video/watch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
