// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/manage/admin.vue')['default']
    Book: typeof import('./src/components/book/book.vue')['default']
    Bookbox: typeof import('./src/components/book/bookbox.vue')['default']
    Bookcontent: typeof import('./src/components/book/bookcontent.vue')['default']
    Bookinfo: typeof import('./src/components/book/bookinfo.vue')['default']
    Bookshelfbox: typeof import('./src/components/book/bookshelfbox.vue')['default']
    Camera: typeof import('./src/components/camera.vue')['default']
    Cataloguebox: typeof import('./src/components/book/cataloguebox.vue')['default']
    Config: typeof import('./src/components/manage/config.vue')['default']
    DrakMode: typeof import('./src/components/DrakMode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FaceRecognition: typeof import('./src/components/FaceRecognition.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Like: typeof import('./src/components/like.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Music: typeof import('./src/components/music.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    Notfound: typeof import('./src/components/notfound.vue')['default']
    Spy: typeof import('./src/components/game/spy.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
  }
}

export { }
